# Generated by Django 3.2.12 on 2022-03-07 10:27

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, help_text='Where the brand offers retails services', max_length=746, multiple=True),
        ),
    ]
