# Generated by Django 3.2.12 on 2022-03-09 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name': 'Commentary', 'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AlterField(
            model_name='commentary',
            name='brand',
            field=models.OneToOneField(blank=True, help_text='What brand is this comment associated with?', on_delete=django.db.models.deletion.CASCADE, related_name='commentary_brand', to='brand.brand'),
        ),
    ]
