# Generated by Django 4.0.5 on 2022-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_commentary_our_take'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='recommended_order',
        ),
        migrations.AddField(
            model_name='commentary',
            name='result_page_variation',
            field=models.CharField(blank=True, choices=[('ran', 'Ran'), ('bimpact', 'Bimpact'), ('fairfinance', 'Fairfinance'), ('gabv', 'Gabv'), ('', 'Blank')], default='', help_text='Used to customize how we display the brand result page on the frontend', max_length=20),
        ),
    ]
