# Generated by Django 3.2.12 on 2022-05-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_auto_20220521_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='graphql_country',
        ),
    ]
