# Generated by Django 3.2.12 on 2022-03-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20220309_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={},
        ),
        migrations.AlterField(
            model_name='commentary',
            name='brand',
            field=models.OneToOneField(help_text='What brand is this comment associated with?', on_delete=django.db.models.deletion.CASCADE, related_name='commentary_brand', to='brand.brand'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='recommended_order',
            field=models.IntegerField(blank=True, help_text='Positive. in case there are more recommended banks than can fit on the page, lower numbers are given priority', null=True),
        ),
    ]
