# Generated by Django 3.2.12 on 2022-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_brand_graphql_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='aba_prim_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='countries_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='cusip_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='description_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='ein_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='fdic_cert_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='googleid_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='isin_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='lei_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='ncua_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='occ_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='permid_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='rssd_hd_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='rssd_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='tag_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='thrift_hc_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='thrift_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='viafid_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='website_locked',
            field=models.BooleanField(default=False),
        ),
    ]
