# Generated by Django 3.2.12 on 2022-03-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_auto_20220309_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='suggested_datasource',
            field=models.TextField(blank=True, default='-blank-', null=True),
        ),
    ]
