# Generated by Django 3.2.12 on 2022-05-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_brand_graphql_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='brand',
            field=models.OneToOneField(help_text='What brand is this comment associated with?', on_delete=django.db.models.deletion.CASCADE, related_name='commentary', to='brand.brand'),
        ),
    ]
