# Generated by Django 3.2.12 on 2022-03-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0004_auto_20220313_1633'),
        ('brand', '0004_brand_suggested_datasource'),
    ]

    operations = [
    ]
