# Generated by Django 4.0.5 on 2022-07-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_featuretype_brandfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.featuretype'),
        ),
        migrations.AddConstraint(
            model_name='brandfeature',
            constraint=models.UniqueConstraint(fields=('feature', 'brand'), name='unique_feature_implementation_per_bank'),
        ),
    ]
