# Generated by Django 3.2.12 on 2022-03-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0005_merge_20220321_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='rating',
            field=models.CharField(choices=[('great', 'Great'), ('ok', 'Ok'), ('bad', 'Bad'), ('worst', 'Worst'), ('unknown', 'Unknown')], default='unknown', max_length=8),
        ),
    ]
