# Generated by Django 4.0.6 on 2022-07-31 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_alter_brandfeature_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='number_of_requests',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
