# Generated by Django 3.2.12 on 2022-03-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0006_alter_commentary_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='graphql_country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
