# Generated by Django 4.0.6 on 2022-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_commentary_number_of_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='amount_financed_since_2016',
            field=models.CharField(blank=True, default=None, help_text='Negative. Amount of fossil fuel investment the brand has financed since the paris accord, i.e. $382 billion USD', max_length=150, null=True),
        ),
    ]
