# Generated by Django 3.2.12 on 2022-04-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0007_brand_graphql_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='suggested_datasource',
        ),
    ]
