# Generated by Django 4.0.6 on 2022-08-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_featuretype_brandfeature_correction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='snippet_1',
            field=models.CharField(blank=True, default='', help_text='Negative. Custom fact about the brand. Used to fill in templates', max_length=300),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='snippet_2',
            field=models.CharField(blank=True, default='', help_text='Negative. Custom fact about the brand. Used to fill in templates', max_length=300),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='snippet_3',
            field=models.CharField(blank=True, default='', help_text='Negative. Custom fact about the brand. Used to fill in templates', max_length=300),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='top_blurb_headline',
            field=models.CharField(blank=True, help_text='Positive/Negative. i.e. Your money is being used to fund the climate crisis at an alarming rate.', max_length=300),
        ),
    ]
