# Generated by Django 4.0.5 on 2022-08-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0009_alter_commentary_snippet_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='certified_fossil_free',
            field=models.BooleanField(default=False, help_text='Is this bank part of the Fossil Free Alliance?'),
        ),
    ]
