# Generated by Django 4.0.5 on 2022-08-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0010_commentary_certified_fossil_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='certified_fossil_free',
        ),
    ]
