# Generated by Django 4.0.7 on 2022-08-17 12:26

from django.db import migrations, models


def correct_feature_data_migration(apps, schema_editor):
    try:
        from brand.models.features import (
            BrandFeature,
            FeatureAvailabilityChoice,
            Features,
            FeatureType,
        )
    except (ImportError, ModuleNotFoundError):
        print("Could not import required models for feature migration. No corrections made")
        return None

    ft_free_checking = FeatureType.objects.get(name="free_checking")

    for feature in Features.objects.all():

        if feature.free_checking:
            brand_feature = BrandFeature.objects.get(brand=feature.brand, feature=ft_free_checking)
            brand_feature.offered = FeatureAvailabilityChoice.YES


class Migration(migrations.Migration):

    dependencies = [("brand", "0011_remove_commentary_certified_fossil_free")]

    operations = [migrations.RunPython(code=correct_feature_data_migration)]
