# Generated by Django 4.0.5 on 2022-08-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0012_fix_feature_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandUpdate',
            fields=[
                ('brand_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='brand.brand')),
                ('additional_info', models.TextField(blank=True, default='', verbose_name='Add any additional information or explanation for this change')),
                ('update_tag', models.CharField(help_text=('the tag we use or this brand record at Bank.Green. ',), max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('brand.brand',),
        ),
    ]
