# Generated by Django 4.0.7 on 2022-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('brand', '0012_fix_feature_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='regions',
            field=models.ManyToManyField(to='cities_light.region'),
        ),
    ]
