# Generated by Django 4.0.7 on 2022-09-01 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0013_brand_regions")]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="fossil_free_alliance_rating",
            field=models.IntegerField(
                default=0,
                help_text="the fossil free alliance rating. Out of 5",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        )
    ]
