# Generated by Django 4.0.7 on 2022-09-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0014_commentary_fossil_free_alliance_rating'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='show_on_sustainable_banks_page',
            field=models.BooleanField(default=False, help_text='Positive. Check if bank should be shown on sustainable banks page.'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='tag',
            field=models.CharField(help_text='the tag we use or this brand record at Bank.Green. ', max_length=100, unique=True),
        ),
    ]
