# Generated by Django 4.0.7 on 2022-09-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('brand', '0014_commentary_fossil_free_alliance_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='regions',
            field=models.ManyToManyField(blank=True, null=True, to='cities_light.region'),
        ),
    ]
