# Generated by Django 4.0.5 on 2022-09-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0014_brandupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandupdate',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='Can we reach out to you via email?'),
        ),
        migrations.AddField(
            model_name='brandupdate',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Your email address'),
        ),
    ]
