# Generated by Django 4.0.7 on 2022-09-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0014_commentary_fossil_free_alliance_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='details',
            field=models.TextField(blank=True, help_text="Markdown. Displayed as the overview of a bank's activities once you scroll down to their second page."),
        ),
        migrations.AddField(
            model_name='commentary',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Markdown. Displayed immediately under the bank name'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='summary',
            field=models.TextField(blank=True, help_text="Markdown. Displayed as the first overview text on a bank's site. Use a heading marker (#) to make the first impact sentence bold."),
        ),
    ]
