# Generated by Django 4.0.7 on 2022-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('brand', '0015_alter_brand_regions_commentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='subregions',
            field=models.ManyToManyField(blank=True, help_text='regions in which there are local branches of a bank', to='cities_light.subregion'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='regions in which there are local branches of a bank', to='cities_light.region'),
        ),
    ]
