# Generated by Django 4.0.7 on 2022-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0015_commentary_details_commentary_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='header',
            field=models.TextField(blank=True, help_text="Markdown. Displayed as the header to the summary on the first page of a bank's site."),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='summary',
            field=models.TextField(blank=True, help_text="Markdown. Displayed as the first overview text on a bank's site."),
        ),
    ]
