# Generated by Django 4.0.7 on 2022-09-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0016_brand_subregions_alter_brand_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='details',
            field=models.TextField(blank=True, help_text="Markdown. Displayed as the overview of a bank's activities once you scroll down to their second page."),
        ),
        migrations.AddField(
            model_name='commentary',
            name='header',
            field=models.TextField(blank=True, help_text="Markdown. Displayed as the header to the summary on the first page of a bank's site."),
        ),
        migrations.AddField(
            model_name='commentary',
            name='subtitle',
            field=models.TextField(blank=True, help_text='Markdown. Displayed immediately under the bank name'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='summary',
            field=models.TextField(blank=True, help_text="Markdown. Displayed as the first overview text on a bank's site."),
        ),
    ]
