# Generated by Django 4.0.7 on 2022-09-15 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0015_alter_brand_regions_commentary'),
        ('brand', '0016_commentary_header_alter_commentary_summary'),
    ]

    operations = [
    ]
