# Generated by Django 4.0.7 on 2022-09-17 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0017_commentary_details_commentary_header_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='fossil_free_alliance_rating',
            field=models.IntegerField(default=-1, help_text='the fossil free alliance rating. Values between -1 and 5. 0 for unknown rating. -1 for not FFA', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
