# Generated by Django 4.0.7 on 2022-12-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0021_brand_inherit_rating_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='aba_prim',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='cusip',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='ein',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='fdic_cert',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='googleid',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='isin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='lei',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='ncua',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='occ',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='permid',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='rssd',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='rssd_hd',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thrift',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='thrift_hc',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='brand',
            name='viafid',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
