# Generated by Django 4.1.4 on 2023-01-06 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("brand", "0022_alter_brand_aba_prim_alter_brand_cusip_and_more")]

    operations = [
        migrations.RemoveField(model_name="brand", name="inherit_rating_from"),
        migrations.AddField(
            model_name="commentary",
            name="inherit_brand_rating",
            field=models.ForeignKey(
                blank=True,
                help_text="should this brand have a rating inherited from another? If so, save will override the existing rating using the parent's rating unless the parent rating is blank.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inherit_brand_rating",
                to="brand.brand",
            ),
        ),
    ]
