# Generated by Django 4.1.4 on 2023-01-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0023_remove_brand_inherit_rating_from_and_more")]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="rating",
            field=models.CharField(
                choices=[
                    ("great", "Great"),
                    ("ok", "Ok"),
                    ("bad", "Bad"),
                    ("worst", "Worst"),
                    ("unknown", "Unknown"),
                    ("inherit", "Inherit"),
                ],
                default="unknown",
                max_length=8,
            ),
        )
    ]
