# Generated by Django 4.1.4 on 2023-01-31 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0024_alter_commentary_rating")]

    operations = [
        migrations.AlterField(
            model_name="brandfeature",
            name="offered",
            field=models.CharField(
                choices=[
                    ("Yes", "Yes"),
                    ("No", "No"),
                    ("Maybe", "Maybe"),
                    ("N/A", "Not Applicable"),
                ],
                default="Yes",
                help_text="Is the feature offered?",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="featuretype",
            name="description",
            field=models.TextField(
                help_text="Description about this feature type. This is displayed on the website."
            ),
        ),
    ]
