# Generated by Django 4.1.4 on 2023-02-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0026_brandupdate")]

    operations = [
        migrations.AddField(
            model_name="featuretype",
            name="allow_filtering",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="brandfeature",
            name="details",
            field=models.CharField(
                blank=True,
                help_text='Details about the feature are displayed on the website without the feature name, so prepend with names. e.g. "interest rates:" 3%',
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="featuretype",
            name="description",
            field=models.TextField(help_text="Description about this feature type."),
        ),
        migrations.DeleteModel(name="Features"),
    ]
