# Generated by Django 4.1.4 on 2023-03-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0027_remove_brand_aba_prim_locked_and_more")]

    operations = [
        migrations.AddField(
            model_name="brandupdate", name="merged", field=models.BooleanField(default=False)
        )
    ]
