# Generated by Django 4.1.4 on 2023-03-31 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0028_brandupdate_merged")]

    operations = [
        migrations.RemoveField(model_name="brand", name="subsidiary_of_1"),
        migrations.RemoveField(model_name="brand", name="subsidiary_of_1_pct"),
        migrations.RemoveField(model_name="brand", name="subsidiary_of_2"),
        migrations.RemoveField(model_name="brand", name="subsidiary_of_2_pct"),
        migrations.RemoveField(model_name="brand", name="subsidiary_of_3"),
        migrations.RemoveField(model_name="brand", name="subsidiary_of_3_pct"),
        migrations.RemoveField(model_name="brand", name="subsidiary_of_4"),
        migrations.RemoveField(model_name="brand", name="subsidiary_of_4_pct"),
        migrations.RemoveField(model_name="commentary", name="headline"),
        migrations.RemoveField(model_name="commentary", name="recommended_in"),
        migrations.RemoveField(model_name="commentary", name="snippet_1"),
        migrations.RemoveField(model_name="commentary", name="snippet_1_link"),
        migrations.RemoveField(model_name="commentary", name="snippet_2"),
        migrations.RemoveField(model_name="commentary", name="snippet_2_link"),
        migrations.RemoveField(model_name="commentary", name="snippet_3"),
        migrations.RemoveField(model_name="commentary", name="snippet_3_link"),
        migrations.RemoveField(model_name="commentary", name="top_blurb_headline"),
        migrations.RemoveField(model_name="commentary", name="top_blurb_subheadline"),
        migrations.RemoveField(model_name="commentary", name="top_three_ethical"),
        migrations.RemoveField(model_name="commentary", name="unique_statement"),
    ]
