# Generated by Django 4.1.7 on 2023-04-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0029_remove_brand_subsidiary_of_1_and_more")]

    operations = [
        migrations.CreateModel(
            name="InstitutionCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="description for internal use", max_length=100
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstitutionType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="description for internal use", max_length=100
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commentary",
            name="institution_credentials",
            field=models.ManyToManyField(
                blank=True, help_text="Positive", to="brand.institutioncredential"
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="institution_type",
            field=models.ManyToManyField(
                blank=True, help_text="Positive", to="brand.institutiontype"
            ),
        ),
    ]
