# Generated by Django 4.1.7 on 2023-04-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0030_institutioncredential_institutiontype_and_more")]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="rating",
            field=models.CharField(
                choices=[
                    ("great", "Great"),
                    ("good", "Good"),
                    ("ok", "Ok"),
                    ("bad", "Bad"),
                    ("worst", "Worst"),
                    ("unknown", "Unknown"),
                    ("inherit", "Inherit"),
                ],
                default="unknown",
                max_length=8,
            ),
        )
    ]
