# Generated by Django 4.1.7 on 2023-05-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("brand", "0032_institutioncredential_prismic_api_id_and_more")]

    operations = [
        migrations.AlterField(
            model_name="institutioncredential",
            name="prismic_api_id",
            field=models.CharField(
                blank=True,
                help_text="the associated prismic API ID. Must match perfectly with the SFIDefaults type related image field. e.g. institution_credentials-gabv'",
                max_length=100,
            ),
        )
    ]