# Generated by Django 4.1.7 on 2023-09-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0035_commentary_top_pick")]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="top_pick",
            field=models.BooleanField(default=False, help_text="Is this brand a top pick?"),
        )
    ]
