# Generated by Django 4.1.7 on 2023-09-30 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("brand", "0036_alter_commentary_top_pick")]

    operations = [
        migrations.CreateModel(
            name="BrandSuggestion",
            fields=[
                (
                    "brand_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        to="brand.brand",
                    ),
                ),
                (
                    "submitter_name",
                    models.CharField(
                        default="unnamed", max_length=100, verbose_name="Name of the submitter"
                    ),
                ),
                (
                    "submitter_email",
                    models.EmailField(
                        blank=True, max_length=100, verbose_name="Email of the submitter"
                    ),
                ),
                (
                    "submission_date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                ("brand_suggestion_id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={"verbose_name_plural": "Brand suggestions"},
            bases=("brand.brand",),
        )
    ]
