# Generated by Django 4.1.7 on 2023-10-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0037_brandsuggestion")]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="semiautomatic_harassment",
            field=models.CharField(
                choices=[("encourage new policy", "Encourage New Policy"), ("none", "None")],
                default="none",
                max_length=20,
                null=True,
            ),
        )
    ]
