# Generated by Django 4.1.7 on 2024-02-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0039_alter_brand_tag_delete_brandupdate")]

    operations = [migrations.DeleteModel(name="BrandSuggestion")]
