# Generated by Django 4.1.7 on 2024-03-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0040_alter_commentary_embrace")]

    operations = [
        migrations.CreateModel(
            name="EmbraceCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField()),
                ("configuration", models.JSONField(blank=True, default=dict)),
            ],
        )
    ]
