# Generated by Django 4.1.7 on 2024-04-01 21:07

import brand.models.embrace_campaign
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0040_alter_commentary_embrace")]

    operations = [
        migrations.CreateModel(
            name="EmbraceCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField()),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        validators=[brand.models.embrace_campaign.validate_configuration],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commentary",
            name="embrace_campaign",
            field=models.ManyToManyField(blank=True, to="brand.embracecampaign"),
        ),
    ]
