# Generated by Django 4.1.7 on 2024-03-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0041_embracecampaign")]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="embrace_campaign",
            field=models.ManyToManyField(blank=True, to="brand.embracecampaign"),
        )
    ]
