# Generated by Django 4.1.7 on 2024-04-09 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0041_embracecampaign_commentary_embrace_campaign")]

    operations = [migrations.RemoveField(model_name="commentary", name="embrace")]
