# Generated by Django 4.1.7 on 2024-05-02 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0042_remove_commentary_embrace")]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fullname", models.CharField(max_length=70)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("brand_tag", models.CharField(max_length=250)),
                ("brand_name", models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name="commentary",
            name="contacts",
            field=models.ManyToManyField(blank=True, to="brand.contact"),
        ),
    ]
