# Generated by Django 4.1.7 on 2024-06-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0043_contact")]

    operations = [
        migrations.AlterModelOptions(name="brand", options={"ordering": ["name"]}),
        migrations.AlterModelOptions(name="commentary", options={"ordering": ["brand"]}),
        migrations.RemoveField(model_name="commentary", name="number_of_requests"),
    ]
