# Generated by Django 5.1 on 2024-08-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0043_contact")]

    operations = [
        migrations.AlterModelOptions(name="brand", options={"ordering": ["name"]}),
        migrations.AlterModelOptions(name="commentary", options={"ordering": ["brand"]}),
        migrations.RemoveField(model_name="commentary", name="number_of_requests"),
    ]
