# Generated by Django 5.0.6 on 2024-09-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0044_alter_brand_options_alter_commentary_options_and_more")]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="feature_json",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="commentary",
            name="feature_refresh_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
