# Generated by Django 5.0.6 on 2024-10-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0046_commentary_feature_override")]

    operations = [
        migrations.RenameField(
            model_name="commentary", old_name="summary", new_name="description1"
        ),
        migrations.RenameField(
            model_name="commentary", old_name="details", new_name="description2"
        ),
        migrations.RenameField(
            model_name="commentary", old_name="from_the_website", new_name="description3"
        ),
        migrations.RenameField(model_name="commentary", old_name="header", new_name="headline"),
    ]
