# Generated by Django 5.0.6 on 2025-02-13 09:55

import brand.models.commentary
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("brand", "0050_remove_commentary_feature_override"),
        ("brand", "0051_commentary_feature_override"),
    ]

    dependencies = [("brand", "0049_commentary_from_the_website")]

    operations = [
        migrations.RemoveField(model_name="commentary", name="feature_override"),
        migrations.AddField(
            model_name="commentary",
            name="feature_override",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provide harvest features in json with valid keys",
                validators=[brand.models.commentary.validate_feature_override],
                verbose_name="Update Feature",
            ),
        ),
    ]
