# Generated by Django 5.0.6 on 2025-02-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0049_commentary_from_the_website")]

    operations = [migrations.RemoveField(model_name="commentary", name="feature_override")]
