# Generated by Django 5.1.5 on 2025-02-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0049_commentary_from_the_website")]

    operations = [migrations.RemoveField(model_name="commentary", name="feature_override")]
