# Generated by Django 5.1.6 on 2025-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0049_commentary_from_the_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, help_text='date of last rating update', null=True),
        ),
    ]
