# Generated by Django 5.1.5 on 2025-02-17 14:44

import brand.models.commentary
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0050_remove_commentary_feature_override")]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="feature_override",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Provide harvest features in json with valid keys",
                validators=[brand.models.commentary.validate_feature_override],
                verbose_name="Update Feature",
            ),
        )
    ]
