# Generated by Django 5.1.5 on 2025-02-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0051_commentary_feature_override")]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="last_reviewed",
            field=models.DateTimeField(
                blank=True, help_text="date of last rating update", null=True
            ),
        )
    ]
