# Generated by Django 5.1.7 on 2025-05-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0052_commentary_last_reviewed")]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="frn",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Financial Registration Number (used by UK regulators)",
            ),
        )
    ]
