# Generated by Django 5.1.7 on 2025-04-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0052_commentary_last_reviewed")]

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                ("tag", models.CharField(max_length=100, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "country_code",
                    models.CharField(
                        choices=[("US", "US"), ("CA", "CA"), ("AU", "AU")], max_length=2
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StateLicensed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brand.brand"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brand.state"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="state_licensed",
            field=models.ManyToManyField(
                blank=True,
                help_text="State in which brand is licensed",
                related_name="state_licensed",
                through="brand.StateLicensed",
                to="brand.state",
            ),
        ),
        migrations.CreateModel(
            name="StatePhysicalBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brand.brand"
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="brand.state"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="state_physical_branch",
            field=models.ManyToManyField(
                blank=True,
                help_text="State in which brand branches are physically located",
                related_name="state_physical_branch",
                through="brand.StatePhysicalBranch",
                to="brand.state",
            ),
        ),
        migrations.AddConstraint(
            model_name="statelicensed",
            constraint=models.UniqueConstraint(
                fields=("brand", "state"), name="unique_brand_state_licensed"
            ),
        ),
        migrations.AddConstraint(
            model_name="statephysicalbranch",
            constraint=models.UniqueConstraint(
                fields=("brand", "state"), name="unique_brand_state_physical"
            ),
        ),
    ]
