# Generated by Django 5.1.5 on 2025-03-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0052_commentary_last_reviewed")]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="FRN",
            field=models.CharField(
                blank=True,
                help_text="Financial Registration Number (FRN) for the credit union",
                max_length=50,
                null=True,
            ),
        )
    ]
