# Generated by Django 5.1.5 on 2025-03-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("brand", "0053_commentary_frn")]

    operations = [
        migrations.RemoveField(model_name="commentary", name="FRN"),
        migrations.AddField(
            model_name="commentary",
            name="frn",
            field=models.CharField(
                blank=True,
                help_text="Financial Registration Number (FRN) for the credit union",
                max_length=50,
                null=True,
            ),
        ),
    ]
