# Generated by Django 5.1.7 on 2025-08-02 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("brand", "0054_state_statelicensed_brand_state_licensed_and_more")]

    operations = [
        migrations.RemoveField(model_name="brand", name="regions"),
        migrations.RemoveField(model_name="brand", name="subregions"),
    ]
