# Generated by Django 5.1.7 on 2026-07-17 10:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("brand", "0055_remove_brand_regions_remove_brand_subregions")]

    operations = [
        migrations.CreateModel(
            name="SwitchSurveyPlanning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("is_agree_privacy", models.BooleanField(default=False)),
                ("is_agree_marketing", models.BooleanField(default=False)),
                ("mailerlite_synced", models.BooleanField(default=False)),
            ],
            options={"ordering": ["-created"]},
        ),
        migrations.CreateModel(
            name="SwitchSurveySubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("moved_from_bank_name", models.CharField(max_length=100)),
                ("moved_to_bank_name", models.CharField(max_length=100)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("GBP", "British Pound"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("CAD", "Canadian Dollar"),
                            ("AUD", "Australian Dollar"),
                        ],
                        max_length=3,
                    ),
                ),
                ("country", django_countries.fields.CountryField(blank=True, max_length=2)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("is_agree_privacy", models.BooleanField(default=False)),
                ("is_agree_marketing", models.BooleanField(default=False)),
                (
                    "moved_from_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switch_survey_moved_from",
                        to="brand.brand",
                    ),
                ),
                (
                    "moved_to_brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="switch_survey_moved_to",
                        to="brand.brand",
                    ),
                ),
            ],
            options={"ordering": ["-created"]},
        ),
        migrations.CreateModel(
            name="SwitchSurveyEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("mailerlite_synced", models.BooleanField(default=False)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emails",
                        to="impact.switchsurveysubmission",
                    ),
                ),
            ],
            options={"verbose_name_plural": "Switch survey emails"},
        ),
        migrations.AddIndex(
            model_name="switchsurveysubmission",
            index=models.Index(fields=["-created"], name="impact_swit_created_12ff3c_idx"),
        ),
    ]
