SELECT DISTINCT ?bank ?bankLabel ?bankDescription ?bankAltLabel ?countryLabel ?website ?permid ?isin ?viafid ?lei ?gid ?parent ?owner (YEAR(?dissolveddate) AS ?deathyear) WHERE {
  { ?bank wdt:P31+ wd:Q22687. }
  UNION
  { ?bank wdt:p31+ wd:Q449067. }
  UNION
  { ?bank wdt:p31+ wd:Q157963. }
  UNION
  { ?bank wdt:p31+ wd:Q3277997. }
  UNION
  { ?bank wdt:p31+ wd:Q745877. }
  ?bank wdt:P31 ?instance;
    wdt:P17 ?country.
  OPTIONAL { ?bank wdt:P576 ?dissolveddate. }
  OPTIONAL { ?bank wdt:P856 ?website. }
  OPTIONAL { ?bank wdt:P2002 ?twitter. }
  OPTIONAL { ?bank wdt:P3347 ?permid. }
  OPTIONAL { ?bank wdt:P946 ?isin. }
  OPTIONAL { ?bank wdt:P214 ?viafid. }
  OPTIONAL { ?bank wdt:P1278 ?lei. }
  OPTIONAL { ?bank wdt:P2671 ?gid. }
  OPTIONAL { ?bank wdt:P749 ?parent. }
  OPTIONAL { ?bank wdt:P127 ?owner. }
  FILTER(NOT EXISTS { ?country wdt:P31 wd:Q3024240. })
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,fr,de,es,it". }
}