read_only_fields = {
    "name",
    "website",
    "countries",
    "tag",
    "permid",
    "isin",
    "viafid",
    "lei",
    "googleid",
    "rssd",
    "rssd_hd",
    "cusip",
    "thrift",
    "thrift_hc",
    "aba_prim",
    "ncua",
    "fdic_cert",
    "occ",
    "ein",
    "source_link",
    "subsidiary_of_1",
    "subsidiary_of_1_pct",
    "subsidiary_of_1",
    "subsidiary_of_1_pct",
    "subsidiary_of_3",
    "subsidiary_of_3_pct",
    "subsidiary_of_4",
    "subsidiary_of_4_pct",
    "source_link",
    "date_added",
    "date_updated",
    "suggested_brands",
}

model_names = [
    "banktrack",
    "bimpact",
    "bocc",
    "datasource",
    "fairfinance",
    "gabv",
    "marketforces",
    "switchit",
    "usnic",
    "wikidata",
]

lev_distance = 10
