# Generated by Django 3.2.7 on 2021-10-02 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('countries', models.CharField(max_length=200)),
                ('permid', models.CharField(max_length=15)),
                ('isin', models.CharField(max_length=15)),
                ('viafid', models.CharField(max_length=15)),
                ('lei', models.CharField(max_length=15)),
                ('googleid', models.CharField(max_length=15)),
                ('wikiid', models.CharField(max_length=15)),
                ('rssd', models.CharField(max_length=15)),
                ('rssd_hd', models.CharField(max_length=15)),
                ('cusip', models.CharField(max_length=15)),
                ('thrift', models.CharField(max_length=15)),
                ('thrift_hc', models.CharField(max_length=15)),
                ('aba_prim', models.CharField(max_length=15)),
                ('ncua', models.CharField(max_length=15)),
                ('fdic_cert', models.CharField(max_length=15)),
                ('occ', models.CharField(max_length=15)),
                ('ein', models.CharField(max_length=15)),
                ('date_added', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
