# Generated by Django 4.0.5 on 2022-06-11 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(default='-unnamed-', max_length=200, verbose_name='Name of this data source')),
                ('source_id', models.CharField(help_text='the original identifier used by the datasource. i.e wikiid, or banktrack tag', max_length=100)),
                ('source_link', models.URLField(blank=True, null=True, verbose_name="Link to the data source's webpage. i.e. the banktrack.org or b-impact webpage for the bank")),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasources', to='brand.brand')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banktrack',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('countries', django_countries.fields.CountryField(blank=True, help_text='Where the bank offers retails services', max_length=746, multiple=True)),
                ('tag', models.CharField(help_text=("Banktrack's own tag, has format bank_of_america",), max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website of this entry. i.e. bankofamerica.com')),
                ('description', models.TextField(blank=True, default='-blank-', null=True, verbose_name='Description of this entry')),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Bimpact',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('description', models.TextField(blank=True, default='-blank-', null=True, verbose_name='Description of this instance of this brand/data source')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website of this brand/data source. i.e. bankofamerica.com')),
                ('countries', django_countries.fields.CountryField(blank=True, help_text='Where the brand offers retails services', max_length=746, multiple=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Bocc',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('countries', django_countries.fields.CountryField(blank=True, help_text='Where the bank offers retails services', max_length=746, multiple=True)),
                ('description', models.TextField(blank=True, default='-blank-', null=True, verbose_name='Description of this instance of this brand/data source')),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Fairfinance',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('countries', django_countries.fields.CountryField(blank=True, help_text='Where the bank offers retails services', max_length=746, multiple=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Gabv',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('description', models.TextField(blank=True, default='-blank-', null=True, verbose_name='Description of this instance of this brand/data source')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website of this brand/data source. i.e. bankofamerica.com')),
                ('countries', django_countries.fields.CountryField(blank=True, help_text='Where the brand offers retails services', max_length=746, multiple=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Marketforces',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Switchit',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website of this brand/data source. i.e. bankofamerica.com')),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Usnic',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('rssd', models.CharField(blank=True, max_length=15)),
                ('rssd_hd', models.CharField(blank=True, max_length=15)),
                ('cusip', models.CharField(blank=True, max_length=15)),
                ('thrift', models.CharField(blank=True, max_length=15)),
                ('thrift_hc', models.CharField(blank=True, max_length=15)),
                ('aba_prim', models.CharField(blank=True, max_length=15)),
                ('ncua', models.CharField(blank=True, max_length=15)),
                ('fdic_cert', models.CharField(blank=True, max_length=15)),
                ('occ', models.CharField(blank=True, max_length=15)),
                ('ein', models.CharField(blank=True, max_length=15)),
                ('lei', models.CharField(blank=True, max_length=15)),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website of this brand/data source. i.e. bankofamerica.com')),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Wikidata',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('permid', models.CharField(blank=True, max_length=15)),
                ('isin', models.CharField(blank=True, max_length=15)),
                ('viafid', models.CharField(blank=True, max_length=15)),
                ('lei', models.CharField(blank=True, max_length=15)),
                ('googleid', models.CharField(blank=True, max_length=15)),
                ('countries', django_countries.fields.CountryField(blank=True, help_text='Where the brand offers retails services', max_length=746, multiple=True)),
                ('description', models.TextField(blank=True, default='-blank-', null=True, verbose_name='Description of this instance of this brand/data source')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website of this brand/data source. i.e. bankofamerica.com')),
            ],
            options={
                'abstract': False,
            },
            bases=('datasource.datasource',),
        ),
    ]
