# Generated by Django 3.2.7 on 2022-01-12 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-unnamed-', max_length=200, verbose_name='Name of this data source')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description of this instance of a data source')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website of this data source')),
                ('countries', models.CharField(max_length=200)),
                ('tag', models.CharField(editable=False, help_text='the tag we use or this datasource record at Bank.Green', max_length=100, unique=True)),
                ('source_id', models.CharField(editable=False, help_text='the original identifier used by the datasource. i.e wikiid, or banktrack tag', max_length=100, unique=True)),
                ('permid', models.CharField(max_length=15)),
                ('isin', models.CharField(max_length=15)),
                ('viafid', models.CharField(max_length=15)),
                ('lei', models.CharField(max_length=15)),
                ('googleid', models.CharField(max_length=15)),
                ('rssd', models.CharField(max_length=15)),
                ('rssd_hd', models.CharField(max_length=15)),
                ('cusip', models.CharField(max_length=15)),
                ('thrift', models.CharField(max_length=15)),
                ('thrift_hc', models.CharField(max_length=15)),
                ('aba_prim', models.CharField(max_length=15)),
                ('ncua', models.CharField(max_length=15)),
                ('fdic_cert', models.CharField(max_length=15)),
                ('occ', models.CharField(max_length=15)),
                ('ein', models.CharField(max_length=15)),
                ('subsidiary_of_1_pct', models.IntegerField(default=0, verbose_name='percentage owned by subsidiary 1')),
                ('subsidiary_of_2_pct', models.IntegerField(default=0, verbose_name='percentage owned by subsidiary 2')),
                ('subsidiary_of_3_pct', models.IntegerField(default=0, verbose_name='percentage owned by subsidiary 3')),
                ('subsidiary_of_4_pct', models.IntegerField(default=0, verbose_name='percentage owned by subsidiary 4')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Time of last update')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank')),
                ('subsidiary_of_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_of_1_data_source', to='datasource.datasource')),
                ('subsidiary_of_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_of_2_data_source', to='datasource.datasource')),
                ('subsidiary_of_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_of_3_data_source', to='datasource.datasource')),
                ('subsidiary_of_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_of_4_data_source', to='datasource.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Banktrack',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('banktrack_link', models.URLField(editable=False, verbose_name='Link to the banktrack bank page')),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Bimpact',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Bocc',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Custombank',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('comment', models.TextField()),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Fairfinance',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Gabv',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Marketforces',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Switchit',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Usnic',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            bases=('datasource.datasource',),
        ),
        migrations.CreateModel(
            name='Wikidata',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
            ],
            bases=('datasource.datasource',),
        ),
    ]
