# Generated by Django 4.0.7 on 2022-12-08 10:21

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usnic',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Country the bank is locatd in', max_length=2),
        ),
        migrations.AddField(
            model_name='usnic',
            name='women_or_minority_owned',
            field=models.BooleanField(default=False),
        ),
    ]
