# Generated by Django 3.2.12 on 2022-03-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='suggested_brands',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
