# Generated by Django 3.2.7 on 2021-10-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(default='-unnamed-', max_length=200),
        ),
    ]
