# Generated by Django 3.2.12 on 2022-03-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_datasource_suggested_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='suggested_brands',
            field=models.TextField(blank=True, null=True),
        ),
    ]
