# Generated by Django 3.2.12 on 2022-05-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0003_remove_brand_graphql_country'),
        ('datasource', '0002_alter_datasource_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasources', to='brand.brand'),
        ),
    ]
