# Generated by Django 3.2.7 on 2021-10-02 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0002_auto_20211002_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTrack',
            fields=[
                ('datasource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasource.datasource')),
                ('update_date', models.DateTimeField(editable=False, help_text='the date that the banktrack data was last refreshed')),
                ('banktrack_link', models.URLField(editable=False, help_text='a link to the banktrack page')),
                ('tag', models.CharField(editable=False, max_length=100)),
            ],
            bases=('datasource.datasource',),
        ),
    ]
