# Generated by Django 4.0.7 on 2022-12-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('datasource', '0002_usnic_country_usnic_women_or_minority_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='usnic',
            name='regions',
            field=models.ManyToManyField(blank=True, help_text='regions in which there are local branches of a bank', to='cities_light.region'),
        ),
        migrations.AddField(
            model_name='usnic',
            name='subregions',
            field=models.ManyToManyField(blank=True, help_text='regions in which there are local branches of a bank', to='cities_light.subregion'),
        ),
    ]
