# Generated by Django 4.0.7 on 2022-12-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0003_usnic_regions_usnic_subregions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usnic',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
