# Generated by Django 3.2.12 on 2022-03-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0003_alter_datasource_suggested_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='suggested_brands',
            field=models.TextField(blank=True, default='-blank-', null=True),
        ),
    ]
