# Generated by Django 3.2.7 on 2021-10-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        ('datasource', '0003_banktrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.bank'),
        ),
        migrations.AlterField(
            model_name='banktrack',
            name='banktrack_link',
            field=models.URLField(editable=False, verbose_name='Link to the banktrack bank page'),
        ),
        migrations.AlterField(
            model_name='banktrack',
            name='update_date',
            field=models.DateTimeField(editable=False, verbose_name='Banktrack data refresh date and time'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description of this instance of a data source'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(default='-unnamed-', max_length=200, verbose_name='Name of this data source'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website of this data source'),
        ),
    ]
