# Generated by Django 5.1.6 on 2025-02-06 19:31

import django_jsonfield_backport.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_suggestedassociation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usnic',
            name='control',
            field=django_jsonfield_backport.models.JSONField(default={}),
        ),
    ]
