# Generated by Django 3.2.7 on 2021-10-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_auto_20211002_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='subsidiary_of_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_of_1_data_source', to='datasource.datasource'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='subsidiary_of_1_pct',
            field=models.IntegerField(default=0, verbose_name='percentage owned by subsidiary 1'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='subsidiary_of_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_of_2_data_source', to='datasource.datasource'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='subsidiary_of_2_pct',
            field=models.IntegerField(default=0, verbose_name='percentage owned by subsidiary 2'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='subsidiary_of_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_of_3_data_source', to='datasource.datasource'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='subsidiary_of_3_pct',
            field=models.IntegerField(default=0, verbose_name='percentage owned by subsidiary 3'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='subsidiary_of_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiary_of_4_data_source', to='datasource.datasource'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='subsidiary_of_4_pct',
            field=models.IntegerField(default=0, verbose_name='percentage owned by subsidiary 4'),
        ),
    ]
