# Generated by Django 3.2.12 on 2022-03-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_alter_datasource_suggested_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='source_id',
            field=models.CharField(help_text='the original identifier used by the datasource. i.e wikiid, or banktrack tag', max_length=100),
        ),
    ]
