# Generated by Django 4.0.7 on 2022-12-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0004_usnic_legal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usnic',
            name='entity_type',
            field=models.CharField(choices=[('Agreement Corporation - Banking', 'Agb'), ('Agreement Corporation - Investment', 'Agi'), ('Bank Holding Company', 'Bhc'), ('Cooperative Bank', 'Cpb'), ('Domestic Branch of a Domestic Bank', 'Dbr'), ('Domestic Entity Other', 'Deo'), ('Data Processing Servicer', 'Dps'), ('Edge Corporation - Domestic Branch', 'Ebr'), ('Edge Corporation - Banking', 'Edb'), ('Edge Corporation - Investment', 'Edi'), ('Foreign Banking Organization as a BHC', 'Fbh'), ('Foreign Bank', 'Fbk'), ('Foreign Banking Organization', 'Fbo'), ('Federal Credit Union', 'Fcu'), ('Foreign Entity Other', 'Feo'), ('Financial Holding Company / BHC (Note: Can be a domestic or foreign-domiciled holding company)', 'Fhd'), ('Financial Holding Company / FBO', 'Fhf'), ('Finance Company', 'Fnc'), ('Federal Savings Bank', 'Fsb'), ('International Bank of a U.S. Depository - Edge or Trust Co.', 'Ibk'), ('Foreign Branch of a U.S. Bank', 'Ibr'), ('Intermediate Holding Company', 'Ihc'), ('Insured Federal Branch of an FBO', 'Ifb'), ('International Non-bank Subs of Domestic Entities', 'Inb'), ('Insured State Branch of an FBO', 'Isb'), ('Non-deposit Trust Company - Member', 'Mtc'), ('National Bank', 'Nat'), ('Non-member Bank', 'Nmb'), ('Non-deposit Trust Company - Non-member', 'Ntc'), ('New York Investment Company', 'Nyi'), ('Non-U.S. Branch managed by a U.S. Branch/Agency of a Foreign Bank for 002’s reporting - Pseudo Twig', 'Pst'), ('Representative Office', 'Rep'), ('Savings & Loan Association', 'Sal'), ('Securities Broker / Dealer', 'Sbd'), ('State Credit Union', 'Scu'), ('Savings and Loan Holding Company', 'Slhc'), ('State Member Bank', 'Smb'), ('State Savings Bank', 'Ssb'), ('Non-U.S. Branch managed by a U.S. Branch/Agency of a Foreign Bank - TWIG', 'Twg'), ('Uninsured Federal Agency of an FBO', 'Ufa'), ('Uninsured Federal Branch of an FBO', 'Ufb'), ('Uninsured State Agency of an FBO', 'Usa'), ('Uninsured State Branch of an FBO', 'Usb'), ('Unknown', 'Unk')], default='Unknown', max_length=100),
        ),
    ]
