# Generated by Django 4.0.7 on 2022-12-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0005_usnic_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usnic',
            name='rssd_hd',
        ),
    ]
