# Generated by Django 3.2.12 on 2022-04-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0008_remove_brand_suggested_datasource'),
        ('datasource', '0005_alter_datasource_source_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='suggested_brands',
        ),
        migrations.AddField(
            model_name='datasource',
            name='suggested_brands',
            field=models.ManyToManyField(related_name='suggested_brands', to='brand.Brand'),
        ),
    ]
