# Generated by Django 4.0.7 on 2022-12-09 13:51

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('datasource', '0006_remove_usnic_rssd_hd'),
    ]

    operations = [
        migrations.AddField(
            model_name='usnic',
            name='control',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
